### ISSUE TITLE
Pretty Wallpaper has stopped.

### ISSUE THREAD

**Issue by shahid-niazi** [vitham/pretty-wallpaper#1]
While starting the application after building .apk it's getting crashed on startup.

**Comment by viettranhoang** [comment]
> While starting the application after building .apk it's getting crashed on startup.

@shahid-niazi  I fixed

**Comment by shahid-niazi** [comment]
Out standing and thank so so so much.....for making great application its working now... only one question .... can we set wallpaper on both lock screen and home screen... with an option to choose between set on home screen, set on lock screen and set on home and lock screen.

**Comment by viettranhoang** [comment]
@shahid-niazi you can set lock screen by edit https://github.com/vitham/pretty-wallpaper/blob/07f2c84459d60e85f9005fdf6a05580a9b332684/app/src/main/java/com/skyfree/prettywallpaper/ShowImageActivity.java#L88 

=
WallpaperManager.getInstance(this).setStream(inputStream, null, true, WallpaperManager.FLAG_LOCK);

**Comment by viettranhoang** [comment]
https://stackoverflow.com/questions/2653954/how-to-set-android-lock-screen-image

**Comment by shahid-niazi** [comment]
Thank you so much again for your replay.....I already checked this thread....But here is a problem, setStream requires api level 24, means most of the devices will be unsupported for the app.
Actually I'm trying to use lower api level like 19 or something like this to support more devices and I'm trying to call default gallery app to set the wallpaper, and I having problem in it, app picker loads correctly by using this `startActivity(new Intent(Intent.ACTION_SET_WALLPAPER));` but gallery app is not getting image form pretty wallpaper. Can you please tell how to do this..... God Bless You........
